### ISSUE TITLE
`2.0.0` release checklist

### ISSUE THREAD

**Issue by George-Payne** [EventStore/EventStore-Client-NodeJS#180]
- [x] #170 (breaking change)
- [x] #178
- [x] #177
- [x] Update readme to use new stream read code #184
- [x] Remove code marked as deprecated   #183
- [x] Add changelog (with migration guide) 
  - [x] For past releases #182
  - [x] Update for `v2.0.0` 
- [ ] Write a blog post explaining changes in `v2.0.0` - https://github.com/EventStore/blog-articles/issues/126
